/// Display name for common base assets. Falls back to the symbol itself
/// for tickers not in this map. We can replace this with a CoinMarketCap
/// or CoinGecko fetch later.
const Map<String, String> coinDisplayNames = {
  'BTC': 'Bitcoin',
  'ETH': 'Ethereum',
  'BNB': 'BNB',
  'SOL': 'Solana',
  'XRP': 'XRP',
  'ADA': 'Cardano',
  'DOGE': 'Dogecoin',
  'TRX': 'TRON',
  'AVAX': 'Avalanche',
  'DOT': 'Polkadot',
  'LINK': 'Chainlink',
  'MATIC': 'Polygon',
  'POL': 'Polygon',
  'LTC': 'Litecoin',
  'BCH': 'Bitcoin Cash',
  'NEAR': 'NEAR Protocol',
  'UNI': 'Uniswap',
  'ATOM': 'Cosmos',
  'XLM': 'Stellar',
  'ETC': 'Ethereum Classic',
  'FIL': 'Filecoin',
  'APT': 'Aptos',
  'ARB': 'Arbitrum',
  'OP': 'Optimism',
  'INJ': 'Injective',
  'SUI': 'Sui',
  'TIA': 'Celestia',
  'SEI': 'Sei',
  'PEPE': 'Pepe',
  'SHIB': 'Shiba Inu',
  'WIF': 'dogwifhat',
  'BONK': 'Bonk',
  'FLOKI': 'FLOKI',
  'CAKE': 'PancakeSwap',
  'AAVE': 'Aave',
  'MKR': 'Maker',
  'CRV': 'Curve DAO',
  'SUSHI': 'SushiSwap',
  'COMP': 'Compound',
  'SNX': 'Synthetix',
  'GRT': 'The Graph',
  'IMX': 'Immutable',
  'STX': 'Stacks',
  'ICP': 'Internet Computer',
  'HBAR': 'Hedera',
  'VET': 'VeChain',
  'ALGO': 'Algorand',
  'EOS': 'EOS',
  'XTZ': 'Tezos',
  'CHZ': 'Chiliz',
  'GALA': 'Gala',
  'AXS': 'Axie Infinity',
  'SAND': 'The Sandbox',
  'MANA': 'Decentraland',
  'CHIP': 'CHIP',
  'TWT': 'Trust Wallet Token',
  'SFP': 'SafePal',
  'ASTER': 'Aster',
  'USDT': 'Tether',
  'USDC': 'USD Coin',
  'DAI': 'Dai',
  'FDUSD': 'First Digital USD',
  'TUSD': 'TrueUSD',
};

String coinNameFor(String symbol) =>
    coinDisplayNames[symbol] ?? symbol;
